### ISSUE TITLE
Can't create a http message

### ISSUE THREAD

**Issue by vilinski** [ronaldschlenker/FsHttp#54]
I'm using FsHttp to create http messages
This is a breaking change by updating a major version from 3.1.0 to 4.0.2. 

```fsharp
let msg =
    httpMsg {
        GET "https://google.com"
    }
```

```
This expression was expected to have type
    'FsHttp.Domain.IContext'
but here has type
    'LazyHttpBuilder<FsHttp.Context.HeaderContext>'
```

I could be wrong, but I have expected such conversion should be in Run, not in Delay as it is right now
https://github.com/ronaldschlenker/FsHttp/blob/master/src/FsHttp/DslCE.fs#L42

**Comment by ronaldschlenker** [comment]
>I could be wrong, but I have expected such conversion should be in Run, not in Delay as it is right now

I think you are right. In this context, it should also work with Delay, but there was a bug in the implemtation. Since no Combine is used, I think that Delay and Run work in the same way here (but it's just a coincidence). From their original semantic, Run seems to be correct here.

I will publish a bugfix version this evening.

**Comment by ronaldschlenker** [comment]
It should work now with 4.0.3:

https://www.nuget.org/packages/SchlenkR.FsHttp/4.0.3
